---
stages:
  - toolchain
  - lint
  - test
  - build
  - release

variables:
   TOOLCHAIN_IMAGE: registry.petuum.com/internal/scalable-ml/autodist/toolchain:ci_latest
   ARTIFACT_ROOT: /data/artifacts

update-toolchain:
   stage: toolchain
   image: registry.petuum.com/internal/devops/docker-dind-jq:1.0
   tags:
      - docker
   before_script:
      - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_URL}
   script:
      - ./docker/toolchain/update_toolchain_image.sh

lint:
   stage: lint
   image: '${TOOLCHAIN_IMAGE}'
   except:
      - master
   tags:
      - docker
   script:
      - prospector autodist

tests:
   stage: test
   image: '${TOOLCHAIN_IMAGE}'
   tags:
     - gpu_runner
   script:
     - 'python3 -m pytest -s --run-integration --cov=autodist --cov-branch --cov-report term-missing --cov-report html:htmlcov tests/'
   artifacts:
     name: cov-report
     paths:
       - htmlcov
     expire_in: '1 day'

build_wheel:
   only:
      - branches
   except:
      - master
      - /^release-.+$/
   stage: build
   tags:
      - docker
   image: python:3.6-slim
   script:
      - apt-get update
      - apt-get install -y git
      - pip install wheel
      - python setup.py bdist_wheel

release_docs:
   only:
      - master
      - /^release-.+$/
      - tags
   stage: release
   image: '${TOOLCHAIN_IMAGE}'
   tags:
      - docker
      - nfs
   script:
      - apt-get update
      - apt-get install -y git make rsync
      - pip install -r docs/requirements-docgen.txt
      - cd docs
      - make apidoc
      - make html
      - mkdir -p ${ARTIFACT_ROOT}/${CI_PROJECT_PATH}
      - rsync -r --delete _build/html ${ARTIFACT_ROOT}/${CI_PROJECT_PATH}
   artifacts:
     name: "docs"
     paths:
       - docs/_build/html
     expire_in: 3 days

release_autodist_wheel:
   only:
      - master
      - /^release-.+$/
      - tags
   stage: release
   tags:
      - docker
   image: python:3.6-slim
   script:
      - apt-get update
      - apt-get install -y git
      - pip install wheel
      # set HOME to the cwd so setuptools picks up the local .pypirc file
      - VERSION=$(./GENVER --pep440) HOME=$(pwd) python setup.py bdist_wheel upload -r http://pypi.int.petuum.com:8080/
