---
stages:
  - toolchain
  - lint
  - test
  - test_dist
  - build
  - release

variables:
   TOOLCHAIN_IMAGE: registry.petuum.com/internal/scalable-ml/autodist/toolchain:ci_latest
   TOOLCHAIN_IMAGE_DIST: registry.petuum.com/internal/scalable-ml/autodist/toolchain:ci_dist
   ARTIFACT_ROOT: /data/artifacts
   # NOTE: don't forget to set the IP in resource_specs

update-toolchain:
   stage: toolchain
   image: registry.petuum.com/internal/devops/docker-dind-jq:1.0
   tags:
      - docker
   before_script:
      - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_URL}
   script:
      - ./docker/toolchain/update_toolchain_image.sh
 
lint:
   stage: lint
   image: '${TOOLCHAIN_IMAGE}'
   except:
      - master
   tags:
      - docker
   script:
      - prospector autodist

tests:
   stage: test
   image: '${TOOLCHAIN_IMAGE}'
   tags:
     - gpu_runner
     - master_node
   script:
     - 'python3 -m pytest -s --run-integration --cov=autodist --cov-branch --cov-report term-missing --cov-report html:htmlcov --ignore=tests/integration/test_dist.py tests/'
   artifacts:
     name: cov-report
     paths:
       - htmlcov
     expire_in: '1 day'

dist_tests:
   stage: test_dist
   only:
      - master
      - /^release-.+$/
   image: '${TOOLCHAIN_IMAGE_DIST}'
   tags:
     - gpu_runner
     - master_node
   before_script:
     # "distribution_trigger.sh is used to manage the autodist repo on target cluster"
     - source scripts/distribution_setup.sh
   script:
     # execution entrance code
     # - ssh -i /tmp/credentials/id_rsa autodist@$NODE1 'bash -c "source /home/autodist/venv/autodist/bin/activate; pytest -s /home/autodist/autodist/tests/integration/test_dist.py"'
     - ssh -i /tmp/credentials/id_rsa autodist@$NODE1 "bash /home/autodist/autodist/scripts/distributed_test_trigger.sh"

build_wheel:
   only:
      - branches
   except:
      - master
      - /^release-.+$/
   stage: build
   tags:
      - docker
   image: python:3.6-slim
   script:
      - apt-get update
      - apt-get install -y git
      - pip install wheel
      - python setup.py bdist_wheel

release_docs:
   only:
      - master
      - /^release-.+$/
      - tags
   stage: release
   image: '${TOOLCHAIN_IMAGE}'
   tags:
      - docker
      - nfs
   script:
      - apt-get update
      - apt-get install -y git make rsync
      - pip install -r docs/requirements-docgen.txt
      - cd docs
      - make apidoc
      - make html
      - mkdir -p ${ARTIFACT_ROOT}/${CI_PROJECT_PATH}
      - rsync -r --delete _build/html ${ARTIFACT_ROOT}/${CI_PROJECT_PATH}
   artifacts:
     name: "docs"
     paths:
       - docs/_build/html
     expire_in: 3 days

release_autodist_wheel:
   only:
      - master
      - /^release-.+$/
      - tags
   stage: release
   tags:
      - docker
   image: python:3.6-slim
   script:
      - apt-get update
      - apt-get install -y git
      - pip install wheel
      # set HOME to the cwd so setuptools picks up the local .pypirc file
      - VERSION=$(./GENVER --pep440) HOME=$(pwd) python setup.py bdist_wheel upload -r http://pypi.int.petuum.com:8080/
