stages:
  - lint
  - build

lint:
   except:
      - master
   stage: lint
   tags:
      - docker
   image: python:3.6-slim
   script:
      - pip install pydocstyle==3.0.0
      - pip install prospector==1.1.6.2
      - prospector

build:
  stage: build
  tags:
    - docker
  script:
    - sh GENVER --pep440
