---
stages:
  - toolchain
  - lint
  - test
  - build
  - release

variables:
   TOOLCHAIN_IMAGE: registry.petuum.com/internal/scalable-ml/autodist/toolchain:ci_latest

update-toolchain:
   stage: toolchain
   image: registry.petuum.com/internal/devops/docker-dind-jq:1.0
   tags:
      - docker
   before_script:
      - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_URL}
   script:
      - ./docker/toolchain/update_toolchain_image.sh

lint:
   stage: lint
   image: '${TOOLCHAIN_IMAGE}'
   except:
      - master
   tags:
      - docker
   script:
      - prospector autodist

test:
   stage: test
   image: '${TOOLCHAIN_IMAGE}'
   tags:
     - docker
   script:
     - 'python3 -m pytest -s --cov=autodist --cov-branch --cov-report term-missing --cov-report html:htmlcov tests/'
   artifacts:
     name: cov-report
     paths:
       - htmlcov
     expire_in: '1 day'

build_wheel:
   only:
      - branches
   except:
      - master
      - /^release-.+$/
   stage: build
   tags:
      - docker
   image: python:3.6-slim
   script:
      - apt-get update
      - apt-get install -y git
      - pip install wheel
      - python setup.py bdist_wheel

release_autodist_wheel:
   only:
      - master
      - /^release-.+$/
      - tags
   stage: release
   tags:
      - docker
   image: python:3.6-slim
   script:
      - apt-get update
      - apt-get install -y git
      - pip install wheel
      # set HOME to the cwd so setuptools picks up the local .pypirc file
      - VERSION=$(./GENVER --pep440) HOME=$(pwd) python setup.py bdist_wheel upload -r http://pypi.int.petuum.com:8080/
